### ISSUE TITLE
sample_xgboost_apps-0.2.2-jar-with-dependencies.jar doesn't have cuda11.2 with libxgboost4j.so

### ISSUE THREAD

**Issue by vonodiripsa** [NVIDIA/spark-rapids-examples#14] opened 2021-08-25 00:28 UTC
**Describe the bug**
XGBoost spark training job failed on cuda 11.2 because it cannot find libxgboost4j.so

**Steps/Code to reproduce bug**
If you follow https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/getting-started-guides/on-prem-cluster/standalone-scala.md
and create sample_xgboost_apps-0.2.2-jar-with-dependencies.jar (from https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.08/docs/get-started/xgboost-examples/building-sample-apps/scala.md ) it doesn't have the path /lib/cuda11.2/ and spark job on cuda 11.2 server cannot find libxgboost4j.so. It has only /lib/cuda11

**Environment details (please complete the following information)**
Spark standalone cluster with cuda 11.2

**Comment by viadea** [comment] 2021-08-25 01:53
Example error:
```
21/08/24 21:25:27 INFO NativeLibLoader: loading /lib/cuda11.2/libxgboost4j.so
21/08/24 21:25:27 ERROR NativeLibLoader: failed to load xgboost4j library from jar
21/08/24 21:25:27 ERROR DMatrix: Failed to load native library
java.io.FileNotFoundException: File /lib/cuda11.2/libxgboost4j.so was not found inside JAR.
        at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:131)
        at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:74)
```

And it is probably due to the jar only has `lib/cuda11/libxgboost4j.so`:
```
jar tf ./mortgage/target/spark_examples_mortgage-0.2.2-jar-with-dependencies.jar  |grep .so$
lib/cuda11/libxgboost4j.so
```

**Comment by GaryShen2008** [comment] 2021-08-25 02:57
@vonodiripsa 
Hi Alexander,
I can't reproduce the issue in my local environment.
Could you please provide the full log? 
It should print some details when loading the library.

**Comment by vonodiripsa** [comment] 2021-08-31 18:09
Gary, this is the file:
https://nvidia-my.sharepoint.com/:u:/p/aspiridonov/EbXjWlxMwIRLlQDoRwnB7bIBWGrJp0TpYRxwac40tYT2nQ?e=Hkqmfy

**Comment by vonodiripsa** [comment] 2021-09-01 00:22
I've checked it again and it works with 21.08. Probably the jar was 21.06 not 21.08

**Comment by GaryShen2008** [comment] 2021-09-01 04:57
> 
> 
> Gary, this is the file:
> https://nvidia-my.sharepoint.com/:u:/p/aspiridonov/EbXjWlxMwIRLlQDoRwnB7bIBWGrJp0TpYRxwac40tYT2nQ?e=Hkqmfy

Yes, it uses xgboost 1.3.0-0.1.0 from branch-21.06.

Since branch 21.08 works, close this issue.

**Closed by GaryShen2008** 2021-09-01 04:57 UTC
Labels: bug
