### ISSUE TITLE
Illegal Argument Exception: features does not exist...

### ISSUE THREAD

**Issue by tristers-at-square** [NVIDIA/spark-rapids-examples#21] opened 2021-09-21 15:58 UTC
**Describe the bug**
When trying to train an XGBoost classifier with GPU's, it produces the following error:

IllegalArgumentException: features does not exist

**Steps/Code to reproduce bug**
Calling the fit method as follows:

val xgbClassifier = new XGBoostClassifier(paramMap)
  .setLabelCol(labelName)
  .setFeaturesCols(featureCols)
xgbClassifier.fit(trainDF)
Expected behavior
I expected the model to successfully train when running on GPU's.

**Environment details (please complete the following information)**

Running Spark job on GCP Dataproc (YARN) with Nvidia Tesla T4 GPU.

The following JAR's are in the /usr/lib/spark/jars/ classPath:

Rapids-4-Spark: rapids-4-spark_2.12-21.08.0.jar
XGBoost4J: xgboost4j_3.0-1.4.2-0.1.0.jar
XGBoost4J-Spark: xgboost4j-spark_3.0-1.4.2-0.1.0.jar
CUDA: cudf-21.08.2-cuda11.jar
Using the following DataProc initializers to install GPU Drivers and Rapids Accelerators:

goog-dataproc-initialization-actions-us-central1/gpu/install_gpu_driver.sh
goog-dataproc-initialization-actions-us-central1/rapids/rapids.sh

Using the following Spark parameter configurations:
"spark.executor.resource.gpu.amount": "1"
"spark.task.resource.gpu.amount": "1"
"spark.rapids.sql.explain": "ALL"
"spark.rapids.sql.concurrentGpuTasks": "2"
"spark.rapids.memory.pinnedPool.size": "2G"
"spark.executor.extraJavaOptions": "-Dai.rapids.cudf.prefer-pinned=true"
"spark.locality.wait": "0s"
"spark.plugins": "com.nvidia.spark.SQLPlugin"
"spark.rapids.sql.hasNans": "false"
"spark.rapids.sql.batchSizeBytes": "512M"
"spark.rapids.sql.reader.batchSizeBytes": "768M"
"spark.rapids.sql.variableFloatAgg.enabled": "true"
"spark.rapids.sql.decimalType.enabled": "true"
"spark.rapids.memory.gpu.pooling.enabled": "false"
"spark.executor.resource.gpu.discoveryScript": "/usr/lib/spark/scripts/gpu/getGpusResources.sh"

**Comment by viadea** [comment] 2021-09-21 21:09
@tristers-at-square  What is the CUDA runtime you are using? 
```
ls -altr /usr/local|grep -i cuda
nvidia-smi
```

**Comment by tristers-at-square** [comment] 2021-09-22 17:58
@viadea It's Cuda 11.2

My Spark job seems to correctly use GPU's when it's doing pre-processing on the data. However, when it gets to the XGBoost training step, it complains about the "features" column being missing. It is my understanding that we shouldn't need to use a VectorAssembler when training with GPU's so I am not sure why that error message is being produced.

**Comment by wbo4958** [comment] 2021-09-23 05:12
@tristers-at-square, Looks like the configuration `"spark.plugins": "com.nvidia.spark.SQLPlugin"` didn't take effect. @viadea Have we tested xgboost on Dataproc?

**Comment by viadea** [comment] 2021-09-23 05:31
@tristers-at-square  I see the rapids.sh is still shown 1.3.0 xgboost jar so does it mean you modified it to use 1.4.2 jar in the init scripts?
```
$ cat rapids.sh |grep -i xgboo
  readonly DEFAULT_XGBOOST_VERSION="1.3.0"
  readonly DEFAULT_XGBOOST_GPU_SUB_VERSION="0.1.0"
  readonly DEFAULT_XGBOOST_VERSION="1.0.0"
  readonly DEFAULT_XGBOOST_GPU_SUB_VERSION="Beta5"
```

**Comment by tristers-at-square** [comment] 2021-09-23 15:50
@viadea I tried both the default configuration in the rapids.sh script and I also tried updating to 1.4.2, but had the same issues either way. Currently, I have the following in my Spark jars classpath on DataProc:

<img width="502" alt="Screen Shot 2021-09-23 at 11 49 12 AM" src="https://user-images.githubusercontent.com/82467782/134540833-decbfe8c-0175-4f3d-bae2-bcbcf3ed2bd5.png">

**Comment by tristers-at-square** [comment] 2021-09-23 15:54
@wbo4958 I am setting the "spark.plugins": "com.nvidia.spark.SQLPlugin" at runtime like so:

```
val spark = SparkSession.builder
                                           .config("spark.plugins", "com.nvidia.spark.SQLPlugin")
                                           // Other Spark configs here
                                           .appName(ApplicationName)
                                           .getOrCreate()
```

**Comment by wbo4958** [comment] 2021-09-24 09:30
@tristers-at-square  Could you give your application sketch and how to set the parameters. then we can repro it. Thx in advance

**Comment by tristers-at-square** [comment] 2021-09-24 16:51
@wbo4958 Sure. For testing purposes, you can simulate the dataset I was using like so (in Python):

```
import pandas
import random
num_features = 7000
num_rows = 30000
data = [[random.random() for _ in range(num_features)] + ["str_feature_value"] + [random.randint(0,1)] for _ in range(num_rows)]
columns = [f"feature{i}" for i in range(num_features)] + ["str_feature"] + ["label"]
df = pandas.DataFrame(data, columns=columns)
df = pandas.to_parquet("path_to_your_parquet_file.pq")
```

Similarly, here's the essentials of the program I was running (nothing fancy):

```
val dataPath = "path_to_your_parquet_file.pq"
val trainDF = spark.read.parquet(dataPath)

val featureColumns = Range(0, 7000).map(x => s"feature${x}") ++ Seq("str_feature_one_hot_encoded")
val stringIndexer = new StringIndexer().setInputCols(Array("str_feature"))
                                       .setOutputCols(Array("str_feature_indexed"))
                                       .setHandleInvalid("keep")
val oneHotEncoder = new OneHotEncoder().setInputCols(Array("str_feature_indexed"))
                                       .setOutputCols(Array("str_feature_one_hot_encoded"))
val xgboostTrainer = new XGBoostClassifier(xgboostParams).setLabelCol("label")
                                                         .setFeaturesCols(featureColumns)
val pipeline = new Pipeline().setStages(Array(
  stringIndexer,
  oneHotEncoder,
  xgboostModel
))
val pipelineModel = pipeline.fit(trainDF)
```

**Comment by wbo4958** [comment] 2021-09-24 23:46
Were you using the notebook for the testing? if that so, the SparkSession may be started up by Dataproc before you explicitly called
``` scala
val spark = SparkSession.builder
                        .config("spark.plugins", "com.nvidia.spark.SQLPlugin")
                         // Other Spark configs here
                        .appName(ApplicationName)
                        .getOrCreate()
```

If that so, the config `config("spark.plugins", "com.nvidia.spark.SQLPlugin")` would not take effect.

One quick suggestion: Could you move the config `config("spark.plugins", "com.nvidia.spark.SQLPlugin")` into the initial script before staring the cluster?

**Comment by firestarman** [comment] 2021-09-25 04:49
You can verify whether the config is taking effect by adding `spark.conf.get("spark.plugins")` just after the creation of the SparkSession.

**Comment by nvliyuan** [comment] 2021-09-27 02:27
@tristers-at-square if it is a notebook, can you please try this command to start?
```
pyspark --master spark://ip:port \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.driver.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} \
  --conf spark.executor.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} \
  --jars ${CUDF_JAR},${RAPIDS_JAR} \
  --py-files ${JAR_PATH}/xgboost4j-spark_XXX.jar;${JAR_PATH}/xgboost4j_XXX.jar;${CUDF_JAR};${RAPIDS_JAR}
```

**Comment by tristers-at-square** [comment] 2021-09-27 18:30
@firestarman Yep, I added a logging statement like so:

```
val spark = SparkSession.builder
                        .config("spark.plugins", "com.nvidia.spark.SQLPlugin")
                         // Other Spark configs here
                        .appName(ApplicationName)
                        .getOrCreate()
logger.warn("ASDFFFFFF")
logger.warn(spark.conf.get("spark.plugins"))
```

And I see the correct expected output in DataProc:

<img width="440" alt="Screen Shot 2021-09-27 at 2 28 07 PM" src="https://user-images.githubusercontent.com/82467782/134965265-3a77b468-1f8d-444e-baef-dd80ef736852.png">


Still getting the same error about "features" not being present though.

**Comment by tristers-at-square** [comment] 2021-09-27 18:32
> Were you using the notebook for the testing? if that so, the SparkSession may be started up by Dataproc before you explicitly called
> 
> ```scala
> val spark = SparkSession.builder
>                         .config("spark.plugins", "com.nvidia.spark.SQLPlugin")
>                          // Other Spark configs here
>                         .appName(ApplicationName)
>                         .getOrCreate()
> ```
> 
> If that so, the config `config("spark.plugins", "com.nvidia.spark.SQLPlugin")` would not take effect.
> 
> One quick suggestion: Could you move the config `config("spark.plugins", "com.nvidia.spark.SQLPlugin")` into the initial script before staring the cluster?

I tried that as well, but am getting the same error about features not being present.

**Comment by tristers-at-square** [comment] 2021-09-27 18:34
> @tristers-at-square if it is a notebook, can you please try this command like this to start?
> 
> ```
> export PYSPARK_DRIVER_PYTHON=jupyter
> export PYSPARK_DRIVER_PYTHON_OPTS='notebook'
> pyspark --master spark://ip:port \
>   --conf spark.plugins=com.nvidia.spark.SQLPlugin \
>   --conf spark.driver.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} \
>   --conf spark.executor.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} \
>   --jars ${CUDF_JAR},${RAPIDS_JAR} \
>   --py-files ${JAR_PATH}/xgboost4j-spark_XXX.jar;${JAR_PATH}/xgboost4j_XXX.jar;${CUDF_JAR};${RAPIDS_JAR}
> ```

@nvliyuan I was running it programmatically through the Google Cloud SDK and I also tried in the Zeppelin notebook. I tried your suggestion by running it in the script through the --conf flags, but am getting the same errors.

As a sanity check, I tried running the mortgage example on the notebook and it failed with the "features" not present error. However, then I tried running the mortgage example on spark-shell and it worked somehow...

**Comment by wbo4958** [comment] 2021-09-28 01:45
@tristers-at-square Thx for the information. So in the case of notebook, seems the "spark.plugins" is not taken effect, which can narrow down the issue.

@nvliyuan Could you help on this? try to run mortgage example on notebook?

**Comment by nvliyuan** [comment] 2021-10-04 11:10
@tristers-at-square 
Hi, do you still have any error while running examples in GCP in GPU?
I tried to run an taxi xgboost demo on GCP, and it works well, here are my steps:

create the GCP cluster with Env:
master: n1-standard-4
worker: n1-standard-16(2 nodes)

cudf-21.08.2-cuda11.jar
rapids-4-spark_2.12-21.08.0.jar
xgboost4j_3.0-1.4.2-0.1.0.jar
xgboost4j-spark_3.0-1.4.2-0.1.0.jar

start a notebook with spark configs:
```
export PYSPARK_DRIVER_PYTHON=jupyter
export JAR_PATH=/home/yuali/jars
export PYSPARK_DRIVER_PYTHON_OPTS='notebook --ip=0.0.0.0 --port=8124'

export CUDF_JAR=/home/yuali/jars/cudf-21.08.2-cuda11.jar
export RAPIDS_JAR=/home/yuali/jars/rapids-4-spark_2.12-21.08.0.jar

pyspark --master yarn \
  --conf spark.executor.resource.gpu.amount=1 \
  --conf spark.task.resource.gpu.amount=1 \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.driver.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} \
  --conf spark.executor.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} \
  --jars ${JAR_PATH}/xgboost4j-spark_3.0-1.4.2-0.1.0.jar,${JAR_PATH}/xgboost4j_3.0-1.4.2-0.1.0.jar,${CUDF_JAR},${RAPIDS_JAR} \
  --py-files ${JAR_PATH}/xgboost4j-spark_3.0-1.4.2-0.1.0.jar;${JAR_PATH}/xgboost4j_3.0-1.4.2-0.1.0.jar;${CUDF_JAR};${RAPIDS_JAR}
```
some changes in the notebook:
```
//the small dataset in the repo : spark-rapids-examples/datasets/taxi-small
train_data = reader.schema(schema).option('header', True).csv('hdfs://XXX/taxi-small/train')
trans_data  = reader.schema(schema).option('header', True).csv('hdfs://XXX/tmp/taxi-small/trainWithEval')
```
```
//save the module:
model.write().overwrite().save('gs://XXXX/new-model-path')
loaded_model = XGBoostRegressionModel().load('gs://XXXX/new-model-path')
```
please let me know if there are still errors.

**Comment by wbo4958** [comment] 2021-10-11 22:19
Oops, I overlook your code. Good catch. Honestly, we didn't test it in Pipeline. I will check that and give some suggestion.

**Comment by viadea** [comment] 2021-10-14 17:22
@wbo4958 is the fix in 1.4.2-0.2.0?

**Comment by wbo4958** [comment] 2021-10-14 21:59
@viadea  Yes. it is

**Comment by nvliyuan** [comment] 2021-11-04 06:35
thanks @wbo4958 for root cause the issue, so @tristers-at-square can I close this issue?

**Comment by tristers-at-square** [comment] 2021-11-04 15:18
> thanks @wbo4958 for root cause the issue, so @tristers-at-square can I close this issue?

Yep, thanks!

**Closed** 2021-11-08 07:33 UTC
