### ISSUE TITLE
Crash in rmm async allocator in test_java_url_decode

### ISSUE THREAD

**Issue by nvdbaranec** [NVIDIA/spark-rapids-examples#349] opened 2024-01-22 20:09 UTC
Build failure in CICD.  Likely upstream of the async allocator itself.

https://prod.blsm.nvidia.com/sw-gpu-spark-jenkins/job/examples-udf-examples-native/121/

```
src/main/python/rapids_udf_test.py::test_java_url_decode

[2024-01-22T09:44:17.989Z] 24/01/22 09:44:17 ERROR RapidsExecutorPlugin: Stopping the Executor based on exception being a fatal
 CUDA error: ai.rapids.cudf.CudaFatalException: std::bad_alloc: CUDA error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-
jni_nightly-dev-652-cuda11/thirdparty/cudf/cpp/build/_deps/rmm-src/include/rmm/mr/device
/cuda_async_view_memory_resource.hpp:128: cudaErrorIllegalAddress an illegal memory access was encountered
```

**Comment by jlowe** [comment] 2024-01-24 21:07
@GaryShen2008 at first I thought this was related to #347, but then upon digging I discovered that's not in the build that failed.  #347 accidentally was committed to main instead of branch-24.02.  :facepalm:

I'll put up reverts to main and re-PR to branch-24.02 to fix that mistake, but the failure noted in this issue may be related to the ccache change in #345, as that's the only change listed between the good run and the failing run.

**Comment by GaryShen2008** [comment] 2024-01-28 09:21
Not reproduced in local. Trigger CI again.

**Comment by NvTimLiu** [comment] 2024-02-05 01:41
checking

**Comment by NvTimLiu** [comment] 2024-02-05 02:15
branch-24.04 UDF examples app with native CUDF is still building to branch-23.12,

https://github.com/NVIDIA/spark-rapids-examples/blob/branch-24.04/examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/CMakeLists.txt#L87-L90

This caused the failure due to

**Comment by NvTimLiu** [comment] 2024-02-08 07:07
Close as fix  https://github.com/NVIDIA/spark-rapids-examples/pull/358  https://github.com/NVIDIA/spark-rapids-examples/pull/359 got merged

**Closed by NvTimLiu** 2024-02-08 07:07 UTC
Labels: bug
